apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  completions: 100
  parallelism: 5
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: example-worker
        image: alpine:3.13
        imagePullPolicy: Always
        command:
        - 'sh'
        - '-c'
        - 'echo "My index: ${JOB_COMPLETION_INDEX}"; sleep 5'
