apiVersion: batch/v1
kind: Job
metadata:
  name: example-job-nfs
spec:
  completions: 100
  parallelism: 5
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: example-worker-nfs
        image: alpine:3.13
        command:
        - 'sh'
        - '-c'
        - 'echo "My index: ${JOB_COMPLETION_INDEX}"; sleep 5'
        volumeMounts:
        - name: nfs-shared
          mountPath: "/shared"
      volumes:
        - name: nfs-shared
          persistentVolumeClaim:
            claimName: nfs
